In [1]:
import numpy as np

In [2]:
ar1=np.array(6)

In [3]:
ar1

array(6)

In [4]:
ar2=np.array([1,2,3,4])

In [5]:
ar2

array([1, 2, 3, 4])

In [6]:
ar3=np.array([12,34,56])

In [7]:
ar3

array([12, 34, 56])

In [8]:
zero_array=np.zeros((1,2))

In [9]:
zero_array

array([[0., 0.]])

In [10]:
ar4=np.arange(5,6,9)

In [11]:
ar4

array([5])

In [12]:
mat1=np.array([[1,2,3],[2,5,7],[4,5,6]])

In [13]:
mat1

array([[1, 2, 3],
       [2, 5, 7],
       [4, 5, 6]])

In [14]:
det_of_mat1=np.linalg.det(mat1)

In [15]:
det_of_mat1

-2.999999999999999

In [16]:
inverse=np.linalg.inv(mat1)

In [17]:
inverse

array([[ 1.66666667, -1.        ,  0.33333333],
       [-5.33333333,  2.        ,  0.33333333],
       [ 3.33333333, -1.        , -0.33333333]])

In [18]:
Dense=np.array([[1,0,3,0],[0,0,0,6],[0,5,6,7],[0,0,1,1]])

In [19]:
Dense

array([[1, 0, 3, 0],
       [0, 0, 0, 6],
       [0, 5, 6, 7],
       [0, 0, 1, 1]])

In [20]:
from scipy.sparse import csr_matrix

In [21]:
sparse=csr_matrix(Dense)

In [22]:
sparse

<4x4 sparse matrix of type '<class 'numpy.intc'>'
	with 8 stored elements in Compressed Sparse Row format>

In [23]:
print(sparse)

  (0, 0)	1
  (0, 2)	3
  (1, 3)	6
  (2, 1)	5
  (2, 2)	6
  (2, 3)	7
  (3, 2)	1
  (3, 3)	1
